/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_8ED19174__
#define __PLUGINEDITOR_H_8ED19174__

#include "genieHeader.h"
#include "PluginProcessor.h"
#include "audioEditor.h"
#include "SequenceEditor.h"
#include "SubsectionEditor.h"

//==============================================================================
/**
 \breif GenieAudioProcessorEditor is the visual parent component of Genie.
 
 It comprises of;
AudioEditor
SequenceEditor
SubsectionEditor
*/
//==============================================================================

class GenieAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    GenieAudioProcessorEditor (GenieAudioProcessor* ownerFilter,
                               drow::AudioFilePlayer& audioFilePlayer_,
                               AudioSubsectionManager &audioSubsectionManager_,
                               PolyAudioFilePlayer &polyAudioFilePlayer_);
    ~GenieAudioProcessorEditor();

    //==============================================================================
    // Component
    void paint (Graphics& g);
    void resized();
    
private:

    SubsectionEditor subsectionEditor;
    AudioEditor audioEditor;
    SequenceEditor sequenceEditor;
    
    
    //==============================================================================
    // Member Objects
    
    //Display
    Label genieTitle;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (GenieAudioProcessorEditor)
};


#endif  // __PLUGINEDITOR_H_8ED19174__
